# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ps_demodoctrine_quote_index:
    path: /demo-doctrine/quotes
    methods: [GET]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::indexAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote'

ps_demodoctrine_quote_search:
    path: /demo-doctrine/quotes
    methods: [POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::searchAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:search'

ps_demodoctrine_quote_generate:
    path: /demo-doctrine/generate
    methods: [GET, POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::generateAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:generate'

ps_demodoctrine_quote_create:
    path: /demo-doctrine/quotes/new
    methods: [GET, POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::createAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:add'

ps_demodoctrine_quote_edit:
    path: /demo-doctrine/quotes/{quoteId}/edit
    methods: [GET, POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::editAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:edit'
    requirements:
        quoteId: \d+

ps_demodoctrine_quote_delete:
    path: /demo-doctrine/quotes/{quoteId}/delete
    methods: [DELETE]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::deleteAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:deletequote'
    requirements:
        quoteId: \d+

ps_demodoctrine_quote_bulk_delete:
    path: /demo-doctrine/quotes/bulkDelete
    methods: [POST]
    defaults:
        _controller: 'Module\DemoDoctrine\Controller\Admin\QuotesController::deleteBulkAction'
        _legacy_controller: 'AdminDemodoctrineQuote'
        _legacy_link: 'AdminDemodoctrineQuote:submitBulkdeletequote'
