# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ps_demoextendsymfonyform_toggle_is_allowed_for_review:
  path: ps_demoextendsymfonyform/{customerId}/toggle-is-allowed-for-review
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\Module\DemoHowToExtendSymfonyForm\Controller\Admin\CustomerReviewController::toggleIsAllowedForReviewAction'
  requirements:
    customerId: \d+
